config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    resources :shifts
    resources :sales_records
    resources :items
    resources :sales_people
    resources :settings
    resources :users

    post 'admin/users', to: 'users#create', as: 'admin_create_user'
    get 'static_pages/dashboard', to: 'static_pages#dashboard', as: 'dashboard'
    get 'sales_people/:id/show_shifts', to: 'sales_people#show_shifts', as: 'show_shifts'
    post "/create_multiple_sales_records", to: "sales_records#create_multiple_sales_records"
  end

  root "static_pages#dashboard"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_user_count, only: [:new, :create]

  def create
    user = User.find_by(email: sign_up_params[:email])

    if user.present?
      flash[:danger] = "An account with this email already exists"
      redirect_to new_user_registration_path
      return
    elsif sign_up_params[:email].blank?
      flash[:danger] = "Enter a email to create an account"
      redirect_to new_user_registration_path
    elsif sign_up_params[:password].blank?
      flash[:danger] = "You must enter a password to create an account"
      redirect_to new_user_registration_path
    elsif sign_up_params[:password_confirmation].blank?
      flash[:danger] = "You must confirm your password to create an account"
      redirect_to new_user_registration_path
    elsif sign_up_params[:first_name].blank? or sign_up_params[:last_name].blank?
      flash[:danger] = "You must fill out your name to create an account"
      redirect_to new_user_registration_path
    elsif sign_up_params[:password] != sign_up_params[:password_confirmation]
      flash[:danger] = "Passwords do not match"
      redirect_to new_user_registration_path
    else
      build_resource(sign_up_params)
      resource.save
      flash[:success] = "Welcome, #{sign_up_params[:first_name]}"
      sign_up(resource_name, resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    end
  end

  private

  def check_user_count
    if User.exists?
      redirect_to new_user_session_path, danger: "Contact a administrator to create an account"
    end
  end

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
    #super
  #end

  # POST /resource/sign_in
  def create
    user = User.find_by(email: sign_in_params[:email])

    if user && user.valid_password?(sign_in_params[:password])
      flash[:success] = "Welcome, #{user.first_name}"
      sign_in_and_redirect user, event: :authentication
    else
      flash[:danger] = "Invalid email or password"
      redirect_to new_user_session_path
    end
  end

  # DELETE /resource/sign_out
  #def destroy
    #super
  #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    #@limit = Setting.first.entity_limit
    #offset = params[:offset].to_i || 0
    #@users = User.all.limit(@limit).offset(offset).order(email: :asc)
    #@total_records = User.all.count

    @users = User.all.order(email: :asc)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, success: 'User was created'
    else
      flash.now[:danger] = @user.errors.full_messages.first
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    session[:return_to] = request.referer
  end

  def update
    user_parameters = user_params
    user_parameters.delete(:password) if user_parameters[:password].blank?

    if @user.update(user_parameters)
      bypass_sign_in(@user) if current_user.id == @user.id
      redirect_to(session.delete(:return_to) || users_path, success: 'User was updated')
    else
      flash.now[:danger] = @user.errors.full_messages.first
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, success: 'User was deleted'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :show_export_buttons) 
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, url: @user.new_record? ? admin_create_user_path : user_path(@user), local: true) do |form| %>
  
  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>First Name</strong></label>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>Last Name</strong></label>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>Email</strong></label>
      <%= form.email_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>Password</strong></label>
      <%= form.text_field :password, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 d-flex justify-content-end">
      <%= form.submit 'Submit', class: 'btn btn-main', data: { turbo: false }, onclick:"show_spinner()" %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to "#{user.first_name} #{user.last_name}", edit_user_path(user), class: "nav-link" %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/edit.html.erb
<div class="flex-fill d-flex flex-column m-1">
  <div id="content-header">
    <div class="row">
      <div class="col-4">
        <%= link_to 'Cancel', :back, class: 'btn btn-main btn-left' %>
      </div>
      <div class="col-4 d-flex justify-content-center">
        <h1>Edit User</h1>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <%= button_to 'Delete', user_path(@user), method: :delete, class: 'btn btn-delete btn-right', hidden: current_user.id == @user.id, onclick: "confirmAndShowSpinner(event, 'Are you sure you want to delete this User?')" %>
      </div>
    </div>
  </div>

  <div class="card m-1" id="content-main">
    <div class="card-body scrollable-form">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
          <%= render "form", user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="d-flex flex-column m-1">

  <div class="row">
    <div class="col-4 d-flex justify-content-start">
      <%= button_to 'Add User', new_user_path, method: :get, data: { turbo: false }, class: 'btn btn-main btn-left' %>
    </div>
    <div class="col-4 d-flex justify-content-center">
      <h1>Users</h1>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <form role="search" class="d-flex search-form">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" id="content-search">
      </form>
    </div>
  </div>
  
  <div class="card m-1 p-2" id="content-main">
    <div class="scrollable-table">
      <% if @users.present? and @users.count > 0 %>
        <table class="table content" id="content-table">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Name</a></th>
              <th class="stick" scope="col"><a>Email</a></th>
            </tr>
          </thead>
          <tbody id="content-table-body">
            <% @users.each do |user| %>
              <%= render 'user', user: user %>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="table content">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Name</a></th>
              <th class="stick" scope="col"><a>Email</a></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        <h1 class="text-center">NO DATA</h1>
      <% end %>

      <div id="loading-spinner" style="display: none; text-align: center;">
        <div class="spinner-border" style="color: #193856;" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>

    <div style="text-align: center;" id="recordCount">
      <b>
        Displaying <span id="currentCount"></span>
        <span id="recordLabel"
          data-singular="User"
          data-plural="Users">
        </span>
      </b>
    </div>
  </div>
</div>

<script>
  function loadMoreRecords() {
    if (isLoading) return;
    console.log("Loading Users");
    $.ajax({
      url: "users",
      data: { offset: offset1 },
      type: 'GET',
      dataType: 'script',
      cache: true,
      beforeSend: function(){
        isLoading = true;
        $("#loading-spinner").show();
      },
      success: function(data) {
        offset1 += <%= Setting.first.entity_limit %>;
        console.log("Loaded Users");
        var rowCount = $('#content-table tbody tr').length;
        $('#currentCount').text(rowCount);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.error("AJAX Error:", textStatus, errorThrown);
      },
      complete: function(){
        isLoading = false;
        $("#loading-spinner").hide();
      }
    });
  }
</script>

app/views/users/index.js.erb
$("#content-table tbody").append(
  '<%= j(render partial: "user", collection: @users, as: :user) %>'
);

app/views/users/new.html.erb
<div class="flex-fill d-flex flex-column m-1">
	<div id="content-header">
		<div class="row">
			<div class="col-4">
				<%= link_to 'Cancel', users_path, class: 'btn btn-main btn-left' %>
			</div>
			<div class="col-4 d-flex justify-content-center">
				<h1>New User</h1>
			</div>
			<div class="col-4">
			</div>
		</div>
	</div>

	<div class="card m-1" id="content-main">
		<div class="card-body">
			<div class="row justify-content-center">
				<div class="col-12 col-md-8 col-lg-6">
					<%= render "form", user: @user %>
				</div>
			</div>
		</div>
	</div>
</div>