config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    resources :shifts
    resources :sales_records
    resources :items
    resources :sales_people
    resources :settings
    resources :users

    post 'admin/users', to: 'users#create', as: 'admin_create_user'
    get 'static_pages/dashboard', to: 'static_pages#dashboard', as: 'dashboard'
    get 'sales_people/:id/show_shifts', to: 'sales_people#show_shifts', as: 'show_shifts'
    post "/create_multiple_sales_records", to: "sales_records#create_multiple_sales_records"
  end

  root "static_pages#dashboard"
end

app/controllers/sales_people_controller.rb
class SalesPeopleController < ApplicationController
  before_action :set_sales_person, only: %i[ show show_shifts edit update destroy ]

  # GET /sales_people or /sales_people.json
  def index
    #@limit = Setting.first.entity_limit
    #offset = params[:offset].to_i || 0
    #@sales_people = SalesPerson.all.includes(:sales_records).limit(@limit).offset(offset).order(first_name: :asc, last_name: :asc)
    #@total_records = SalesPerson.all.count

    @sales_people = SalesPerson.all.includes(:sales_records).order(first_name: :asc, last_name: :asc)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /sales_people/1 or /sales_people/1.json
  def show
    @sales_records = @sales_person.sales_records.includes(:item).order(id: :desc)
    @total_records = SalesRecord.where(sales_person_id: @sales_person.id).count

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show_shifts
    @shifts = Shift.where(sales_person_id: @sales_person.id).order(id: :desc)
  end

  # GET /sales_people/new
  def new
    @sales_person = SalesPerson.new
  end

  # GET /sales_people/1/edit
  def edit
  end

  # POST /sales_people or /sales_people.json
  def create
    @sales_person = SalesPerson.new(sales_person_params)
    if @sales_person.save
      redirect_to sales_people_path, success: 'Sales Person was created'
    else
      flash.now[:danger] = @sales_person.errors.full_messages.first
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sales_people/1 or /sales_people/1.json
  def update
    if @sales_person.update(sales_person_params)
      redirect_to sales_people_path, success: 'Sales Person was updated'
    else
      flash.now[:danger] = @sales_person.errors.full_messages.first
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /sales_people/1 or /sales_people/1.json
  def destroy
    @sales_person.destroy
    respond_to do |format|
      format.html { redirect_to sales_people_path, success: 'Sales Person was deleted' }
      format.json do
        @sales_person.destroyed? ? head(:no_content) :
        render(json: { errors: @sales_person.errors.full_messages }, status: :unprocessable_entity)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_person
      @sales_person = SalesPerson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sales_person_params
      params.require(:sales_person).permit(:first_name, :last_name)
    end
end

app/helpers/sales_people_helper.rb
module SalesPeopleHelper
end

app/views/sales_people/_form.html.erb
<%= form_with(model: sales_person) do |form| %>
  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>First Name</strong></label>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="row g-3 mb-3 align-items-center">
    <div class="col-12">
      <label class="col-form-label"><strong>Last Name</strong></label>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 d-flex justify-content-end">
      <%= form.submit 'Submit', class: 'btn btn-main', data: { turbo: false }, onclick:"show_spinner()" %>
    </div>
  </div>
<% end %>

app/views/sales_people/_sales_person.html.erb
<tr>
  <td><%= link_to sales_person.first_name + " " + sales_person.last_name, edit_sales_person_path(sales_person), class: "nav-link" %></td>

  <td>
    <div class="d-flex align-items-center">  
      <% unless sales_person.sales_records.present? or sales_person.shifts.present? %>
        <button class="btn btn-delete" type="button"
          data-entity="sales_people"
          data-entity-name="Sales Person"
          data-id="<%= sales_person.id %>"
          onclick="deleteEntity(event)">
          Delete
        </button>
      <% else %>
        <% if sales_person.sales_records.present? %>
          <%= button_to 'View Sales Records', sales_person_path(sales_person),
          method: :get, data: { turbo: false }, class: 'btn btn-main mt-0' %>
        <% end %>
        <% if sales_person.shifts.present? %>
          <%= button_to 'View Shifts', show_shifts_path(sales_person),
          method: :get, data: { turbo: false }, class: 'btn btn-main mt-0 ms-2' %>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/sales_people/edit.html.erb
<div class="flex-fill d-flex flex-column m-1">
  <div id="content-header">
    <div class="row">
      <div class="col-4">
        <%= link_to 'Cancel', sales_people_path, class: 'btn btn-main btn-left' %>
      </div>
      <div class="col-4 d-flex justify-content-center">
        <h1>Edit Sales Person</h1>
      </div>
      <div class="col-4 d-flex justify-content-end">
      </div>
    </div>
  </div>

  <div class="card m-1" id="content-main">
    <div class="card-body">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
          <%= render "form", sales_person: @sales_person %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sales_people/index.html.erb
<div class="d-flex flex-column m-1">

  <div class="row">
    <div class="col-4 d-flex justify-content-start">
      <%= button_to 'Add Sales Person', new_sales_person_path, method: :get, data: { turbo: false }, class: 'btn btn-main btn-left' %>
    </div>
    <div class="col-4 d-flex justify-content-center">
      <h1>Sales People</h1>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <form role="search" class="d-flex search-form">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" id="content-search">
      </form>
    </div>
  </div>
  
  <div class="card m-1 p-2" id="content-main">
    <div class="scrollable-table">
      <% if @sales_people.present? and @sales_people.count > 0 %>
        <table class="table content" id="content-table">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Name</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody id="content-table-body">
            <% @sales_people.each do |sales_person| %>
              <%= render 'sales_person', sales_person: sales_person %>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="table content">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Name</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        <h1 class="text-center">NO DATA</h1>
      <% end %>

      <div id="loading-spinner" style="display: none; text-align: center;">
        <div class="spinner-border" style="color: #193856;" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>

    <div style="text-align: center;" id="recordCount">
      <b>
        Displaying <span id="currentCount"></span> 
        <span id="recordLabel"
          data-singular="Sales Person"
          data-plural="Sales People">
        </span>
      </b>
    </div>
  </div>
</div>

<script>
  function loadMoreRecords() {
    if (isLoading) return;
    console.log("Loading Sales People");
    const currentVisibleCount = $('#content-table tbody tr').length;

    $.ajax({
      url: "sales_people",
      data: { offset: currentVisibleCount },
      type: 'GET',
      dataType: 'script',
      cache: true,
      beforeSend: function(){
        isLoading = true;
        $("#loading-spinner").show();
      },
      success: function(data) {
        console.log("Loaded Sales People");
        var rowCount = $('#content-table tbody tr').length;
        $('#currentCount').text(rowCount);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.error("AJAX Error:", textStatus, errorThrown);
      },
      complete: function(){
        isLoading = false;
        $("#loading-spinner").hide();
      }
    });
  }
</script>

app/views/sales_people/index.js.erb
$("#content-table tbody").append(
  '<%= j(render partial: "sales_person", collection: @sales_people, as: :sales_person) %>'
);

app/views/sales_people/new.html.erb
<div class="flex-fill d-flex flex-column m-1">
	<div id="content-header">
		<div class="row">
			<div class="col-3">
				<%= link_to 'Cancel', sales_people_path, class: 'btn btn-main btn-left' %>
			</div>
			<div class="col-5 d-flex justify-content-center">
				<h1>New Sales Person</h1>
			</div>
			<div class="col-4">
			</div>
		</div>
	</div>

	<div class="card m-1" id="content-main">
		<div class="card-body scrollable-form">
			<div class="row justify-content-center">
				<div class="col-12 col-md-8 col-lg-6">
					<%= render "form", sales_person: @sales_person %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/sales_people/show.html.erb
<div class="d-flex flex-column m-1">

  <div class="row">
    <div class="col-3 d-flex justify-content-start">
      <%= button_to 'Cancel', sales_people_path, method: :get, data: { turbo: false }, class: 'btn btn-main btn-left' %>
    </div>
    <div class="col-5 d-flex justify-content-center">
      <h1><%= @sales_person.first_name + " " + @sales_person.last_name %></h1>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <form role="search" class="d-flex search-form">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" id="content-search">
      </form>
    </div>
  </div>
  
  <div class="card m-1 p-2" id="content-main">
    <div class="scrollable-table">
      <% if @sales_records.present? and @sales_records.count > 0 %>
        <table class="table content" id="content-table">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Item</a></th>
              <th class="stick" scope="col"><a>Price</a></th>
              <th class="stick" scope="col"><a>Sell Date</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody id="content-table-body">
            <% @sales_records.each do |sales_record| %>
              <tr>
                <td><%= link_to sales_record.item.name, edit_sales_record_path(sales_record), class: "nav-link" %></td>
                <td><%= sales_record.item_price %></td>
                <td><%= sales_record.sell_date.strftime("%m/%d/%Y") %></td>
                <td>
                  <button class="btn btn-delete"
                    data-entity="sales_records"
                    data-entity-name="Sales Record"
                    data-id="<%= sales_record.id %>"
                    onclick="deleteEntity(event)">
                    Delete
                  </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="table content">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Sell Date</a></th>
              <th class="stick" scope="col"><a>Item</a></th>
              <th class="stick" scope="col"><a>Price</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        <h1 class="text-center">NO DATA</h1>
      <% end %>

      <div id="loading-spinner" style="display: none; text-align: center;">
        <div class="spinner-border" style="color: #193856;" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>

    <div style="text-align: center;" id="recordCount">
      <b>
        Displaying <span id="currentCount"></span> 
        <span id="recordLabel"
          data-singular="Sales Record"
          data-plural="Sales Records">
        </span>
      </b>
    </div>
  </div>
</div>

app/views/sales_people/show_shifts.html.erb
<div class="d-flex flex-column m-1">

  <div class="row">
    <div class="col-3 d-flex justify-content-start">
      <%= button_to 'Cancel', sales_people_path, method: :get, data: { turbo: false }, class: 'btn btn-main btn-left' %>
    </div>
    <div class="col-5 d-flex justify-content-center">
      <h1><%= @sales_person.first_name + " " + @sales_person.last_name %></h1>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <form role="search" class="d-flex search-form">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" id="content-search">
      </form>
    </div>
  </div>
  
  <div class="card m-1 p-2" id="content-main">
    <div class="scrollable-table">
      <% if @shifts.present? and @shifts.count > 0 %>
        <table class="table content" id="content-table">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Shift Date</a></th>
              <th class="stick" scope="col"><a>Sales Floor Hours</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody id="content-table-body">
            <% @shifts.each do |shift| %>
              <tr>
                <td><%= link_to shift.shift_date.strftime("%m/%d/%Y"), edit_shift_path(shift), class: "nav-link" %></td>
                <td><%= shift.sales_floor_hours %></td>
                <td>
                  <button class="btn btn-delete"
                    data-entity="shifts"
                    data-entity-name="Shift"
                    data-id="<%= shift.id %>"
                    onclick="deleteEntity(event)">
                    Delete
                  </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <table class="table content">
          <thead>
            <tr>
              <th class="stick" scope="col"><a>Shift Date</a></th>
              <th class="stick" scope="col"><a>Sales Floor Hours</a></th>
              <th class="stick" scope="col"><a></a></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        <h1 class="text-center">NO DATA</h1>
      <% end %>

      <div id="loading-spinner" style="display: none; text-align: center;">
        <div class="spinner-border" style="color: #193856;" role="status">
          <span class="sr-only"></span>
        </div>
      </div>
    </div>

    <div style="text-align: center;" id="recordCount">
      <b>
        Displaying <span id="currentCount"></span> 
        <span id="recordLabel"
          data-singular="Shift"
          data-plural="Shifts">
        </span>
      </b>
    </div>
  </div>
</div>